---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - automation
    reviewers:
      - "elastic/security-external-integrations"
    open-pull-requests-limit: 10
